-- SPA Database Schema v1.0 — PostgreSQL flavour
-- BL-008 Phase 1: scaffold only. Not yet wired into init_db.py.
--
-- Differences vs schema.sql (SQLite):
--   * INTEGER PRIMARY KEY AUTOINCREMENT  -> SERIAL PRIMARY KEY
--   * REAL                               -> DOUBLE PRECISION
--   * TEXT timestamp DEFAULTs using SQLite strftime()/datetime() have been
--     replaced with TIMESTAMPTZ DEFAULT NOW() where the column was a
--     plain timestamp, or removed entirely (with a comment) where the
--     SQLite DEFAULT was generating a structured identifier — those will
--     be generated by application code in Phase 2.
--   * `INTEGER` boolean flags kept as `INTEGER` (NOT changed to BOOLEAN)
--     to minimise data-mapping churn in Phase 2; can be tightened later.
--   * PRAGMA directives removed; equivalent behaviour is the Postgres
--     default (foreign keys are always enforced; WAL has no analogue).

-- PRAGMA journal_mode = WAL;        -- N/A on PostgreSQL
-- PRAGMA foreign_keys = ON;         -- N/A on PostgreSQL (always enforced)

-- ─── protocols ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS protocols (
    id              SERIAL PRIMARY KEY,
    key             TEXT NOT NULL UNIQUE,
    protocol        TEXT NOT NULL,
    asset           TEXT NOT NULL,
    chain           TEXT NOT NULL,
    tier            TEXT NOT NULL,
    pool_id         TEXT,
    is_active       INTEGER NOT NULL DEFAULT 1,
    added_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    notes           TEXT
);

-- ─── apy_snapshots ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS apy_snapshots (
    id                    SERIAL PRIMARY KEY,
    -- snapshot_id was DEFAULT strftime('%Y%m%d_%H%M%S', ...) in SQLite.
    -- In Postgres the application generates it (Phase 2 call-site change).
    snapshot_id           TEXT NOT NULL,
    timestamp             TEXT NOT NULL,
    protocol_key          TEXT NOT NULL,
    protocol              TEXT NOT NULL,
    asset                 TEXT NOT NULL,
    chain                 TEXT NOT NULL,
    tier                  TEXT NOT NULL,
    pool_id               TEXT,
    apy_total             DOUBLE PRECISION NOT NULL,
    apy_base              DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    apy_reward            DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    tvl_usd               DOUBLE PRECISION NOT NULL,
    utilization_rate      DOUBLE PRECISION,
    is_valid              INTEGER NOT NULL DEFAULT 1,
    validation_warnings   TEXT,
    raw_json              TEXT,

    FOREIGN KEY (protocol_key) REFERENCES protocols(key)
);

CREATE INDEX IF NOT EXISTS idx_snapshots_protocol_time
    ON apy_snapshots (protocol_key, timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_snapshots_timestamp
    ON apy_snapshots (timestamp DESC);

-- ─── paper_trades ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS paper_trades (
    id              SERIAL PRIMARY KEY,
    -- trade_id was DEFAULT 'PT-' || strftime(...) in SQLite. Application
    -- generates it on insert in Phase 2.
    trade_id        TEXT NOT NULL UNIQUE,
    strategy_id     TEXT NOT NULL,
    timestamp_open  TEXT NOT NULL,
    timestamp_close TEXT,
    protocol_key    TEXT NOT NULL,
    asset           TEXT NOT NULL,
    action          TEXT NOT NULL,
    amount_usd      DOUBLE PRECISION NOT NULL,
    apy_at_open     DOUBLE PRECISION,
    apy_at_close    DOUBLE PRECISION,
    pnl_usd         DOUBLE PRECISION,
    pnl_pct         DOUBLE PRECISION,
    net_apy_annualized  DOUBLE PRECISION,
    sharpe_contribution DOUBLE PRECISION,
    reason          TEXT,
    risk_check_passed INTEGER NOT NULL DEFAULT 1,
    notes           TEXT,

    FOREIGN KEY (protocol_key) REFERENCES protocols(key)
);

CREATE INDEX IF NOT EXISTS idx_trades_strategy
    ON paper_trades (strategy_id, timestamp_open DESC);

CREATE INDEX IF NOT EXISTS idx_trades_protocol
    ON paper_trades (protocol_key, timestamp_open DESC);

-- ─── risk_events ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS risk_events (
    id              SERIAL PRIMARY KEY,
    timestamp       TEXT NOT NULL,
    event_type      TEXT NOT NULL,
    severity        TEXT NOT NULL,
    protocol_key    TEXT,
    message         TEXT NOT NULL,
    details_json    TEXT,
    resolved        INTEGER NOT NULL DEFAULT 0,
    resolved_at     TEXT,
    resolved_by     TEXT
);

CREATE INDEX IF NOT EXISTS idx_risk_events_time
    ON risk_events (timestamp DESC);

CREATE INDEX IF NOT EXISTS idx_risk_events_severity
    ON risk_events (severity, resolved);

-- ─── strategy_state ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS strategy_state (
    id              SERIAL PRIMARY KEY,
    strategy_id     TEXT NOT NULL,
    timestamp       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    total_capital_usd    DOUBLE PRECISION NOT NULL DEFAULT 10000.0,
    deployed_capital_usd DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    cash_usd             DOUBLE PRECISION NOT NULL DEFAULT 10000.0,
    total_pnl_usd        DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    total_pnl_pct        DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    current_apy          DOUBLE PRECISION,
    sharpe_to_date       DOUBLE PRECISION,
    max_drawdown_pct     DOUBLE PRECISION,
    trade_count          INTEGER NOT NULL DEFAULT 0,
    state_json           TEXT
);

CREATE INDEX IF NOT EXISTS idx_strategy_state
    ON strategy_state (strategy_id, timestamp DESC);

-- ─── message_bus ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS message_bus (
    id              SERIAL PRIMARY KEY,
    message_id      TEXT NOT NULL UNIQUE,
    topic           TEXT NOT NULL,
    sender          TEXT NOT NULL,
    consumer        TEXT,
    payload_json    TEXT NOT NULL,
    priority        INTEGER NOT NULL DEFAULT 5,
    status          TEXT NOT NULL DEFAULT 'pending',
    timestamp       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    consumed_at     TEXT,
    acked_at        TEXT
);

CREATE INDEX IF NOT EXISTS idx_bus_topic_status
    ON message_bus (topic, status, priority, timestamp);

CREATE INDEX IF NOT EXISTS idx_bus_message_id
    ON message_bus (message_id);

-- ─── agent_decisions ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS agent_decisions (
    id                  SERIAL PRIMARY KEY,
    timestamp           TEXT NOT NULL,
    agent_name          TEXT NOT NULL,
    decision_type       TEXT NOT NULL,
    protocol_key        TEXT,
    amount_usd          DOUBLE PRECISION,
    reasoning           TEXT NOT NULL,
    data_snapshot       TEXT,
    policy_version      TEXT DEFAULT 'v1.0',
    strategy_id         TEXT DEFAULT 'paper-v1',
    risk_check_result   TEXT,
    outcome             TEXT
);

CREATE INDEX IF NOT EXISTS idx_agent_decisions_agent ON agent_decisions(agent_name);
CREATE INDEX IF NOT EXISTS idx_agent_decisions_time  ON agent_decisions(timestamp);
CREATE INDEX IF NOT EXISTS idx_agent_decisions_type  ON agent_decisions(decision_type, protocol_key);
