"""
_protocol_blindness.py — эмпирическая разметка протокол-слепых Tier-B модулей.

СГЕНЕРИРОВАНО scripts/audit_protocol_blindness.py — НЕ редактировать вручную;
перегенерация: python3 scripts/audit_protocol_blindness.py --emit-markup
(в sandbox-чекауте, не в живом репо — модули пишут data/*-логи).

Дифференциальный аудит 2026-09-02T07:06:12.420428Z: каждый Tier-B модуль прогнан для
['aave_v3', 'maple', 'pendle'] + повтор aave_v3 (недетерминизм) + контрольный
несуществующий протокол; trio-слепые дополнительно прогнаны по ВСЕЙ
вселенной _protocol_facts (волна 2, задача A2). Модули PROTOCOL_BLIND_DETAIL
вернули «ok», но их score НЕ зависит от протокола (или недетерминирован) →
протокол-специфичной информации не несут. signal_aggregator.run_tier_b
исключает их из composite и из confidence (громкий статус "blind"),
advisory-слой; Tier-A не трогаем.

WIDE_OK_MODULES — модули, равные на аудиторской тройке (весь ethereum), но
РАЗЛИЧАЮЩИЕ протоколы на широкой вселенной (chain/kind/fee-структура):
честные coarse-модули, НЕ слепые, из исполнения НЕ исключаются.
"""
from typing import Dict, FrozenSet

AUDIT_GENERATED_AT = "2026-09-02T07:06:12.420428Z"

# module_name -> подтип (blind_constant | blind_equal | nondeterministic)
PROTOCOL_BLIND_DETAIL: Dict[str, str] = {
    "collateral_health_monitor": "blind_equal",
    "defi_correlation_risk_analyzer": "blind_equal",
    "defi_cross_chain_yield_comparator": "blind_equal",
    "defi_governance_token_utility_scorer": "blind_equal",
    "defi_insurance_protocol_scorer": "blind_equal",
    "defi_liquidity_concentration_risk_scorer": "blind_equal",
    "defi_portfolio_rebalancing_trigger_analyzer": "blind_equal",
    "defi_portfolio_stress_tester": "blind_equal",
    "defi_protocol_autocompound_keeper_reliability_analyzer": "blind_constant",
    "defi_protocol_borrowing_power_utilization_analyzer": "blind_constant",
    "defi_protocol_cdp_stability_fee_analyzer": "blind_constant",
    "defi_protocol_cross_asset_correlation_risk_analyzer": "blind_equal",
    "defi_protocol_deposit_cap_headroom_analyzer": "blind_constant",
    "defi_protocol_depositor_concentration_analyzer": "blind_constant",
    "defi_protocol_insurance_fund_adequacy_analyzer": "blind_equal",
    "defi_protocol_lending_market_health_scorer": "blind_constant",
    "defi_protocol_nft_collateral_risk_analyzer": "blind_equal",
    "defi_protocol_performance_fee_crystallization_frequency_analyzer": "blind_constant",
    "defi_protocol_performance_fee_high_water_mark_analyzer": "blind_constant",
    "defi_protocol_points_to_token_conversion_risk_analyzer": "blind_constant",
    "defi_protocol_real_yield_vs_incentive_yield_analyzer": "blind_constant",
    "defi_protocol_restaking_risk_analyzer": "blind_constant",
    "defi_protocol_stablecoin_par_redemption_capacity_analyzer": "blind_constant",
    "defi_protocol_staking_penalty_risk_analyzer": "blind_constant",
    "defi_protocol_staking_withdrawal_queue_analyzer": "blind_constant",
    "defi_protocol_vault_apr_source_dispersion_analyzer": "blind_constant",
    "defi_protocol_vault_apy_compounding_basis_overstatement_analyzer": "blind_constant",
    "defi_protocol_vault_boost_tier_headline_realization_analyzer": "blind_constant",
    "defi_protocol_vault_bribe_dependency_analyzer": "blind_constant",
    "defi_protocol_vault_capacity_dilution_analyzer": "blind_constant",
    "defi_protocol_vault_denomination_currency_yield_basis_analyzer": "blind_constant",
    "defi_protocol_vault_depeg_recovery_analyzer": "blind_constant",
    "defi_protocol_vault_deployment_ramp_drag_analyzer": "blind_constant",
    "defi_protocol_vault_deposit_activation_lag_analyzer": "blind_constant",
    "defi_protocol_vault_depositor_exit_velocity_analyzer": "blind_constant",
    "defi_protocol_vault_dollar_weighted_return_gap_analyzer": "blind_constant",
    "defi_protocol_vault_early_exit_yield_forfeiture_analyzer": "blind_constant",
    "defi_protocol_vault_entry_exit_fee_amortization_analyzer": "blind_constant",
    "defi_protocol_vault_entry_fee_amortization_analyzer": "blind_constant",
    "defi_protocol_vault_failed_harvest_gas_drag_analyzer": "blind_constant",
    "defi_protocol_vault_funding_rate_carry_persistence_analyzer": "blind_constant",
    "defi_protocol_vault_harvest_cycle_entry_timing_analyzer": "blind_constant",
    "defi_protocol_vault_harvest_timing_analyzer": "blind_constant",
    "defi_protocol_vault_harvest_yield_concentration_analyzer": "blind_constant",
    "defi_protocol_vault_headline_yield_honesty_composite_analyzer": "blind_constant",
    "defi_protocol_vault_idle_cash_drag_analyzer": "blind_constant",
    "defi_protocol_vault_instant_exit_nav_discount_analyzer": "blind_constant",
    "defi_protocol_vault_leveraged_carry_spread_compression_analyzer": "blind_constant",
    "defi_protocol_vault_management_fee_on_idle_capital_analyzer": "blind_constant",
    "defi_protocol_vault_marginal_deposit_apr_dilution_analyzer": "blind_constant",
    "defi_protocol_vault_maturity_track_record_analyzer": "blind_constant",
    "defi_protocol_vault_net_of_loss_yield_realization_analyzer": "blind_constant",
    "defi_protocol_vault_pending_harvest_premium_analyzer": "blind_constant",
    "defi_protocol_vault_performance_fee_catch_up_clause_gap_analyzer": "blind_constant",
    "defi_protocol_vault_performance_fee_cross_sleeve_netting_gap_analyzer": "blind_constant",
    "defi_protocol_vault_performance_fee_gross_of_avs_operator_fee_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_bad_debt_socialization_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_blob_fee_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_boost_fee_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_borrow_cost_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_bridge_fee_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_bundler_fee_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_cost_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_crosschain_message_fee_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_curator_fee_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_deposit_fee_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_flash_loan_fee_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_funding_cost_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_harvest_bounty_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_impermanent_loss_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_insurance_fund_premium_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_insurance_premium_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_intent_solver_fee_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_keeper_fee_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_l1_data_fee_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_liquidation_penalty_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_mev_tax_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_oracle_update_fee_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_priority_fee_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_rebalancing_cost_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_referral_fee_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_reserve_contribution_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_slashing_loss_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_validator_commission_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_gross_of_validator_mev_tax_base_gap_analyzer": "blind_constant",
    "defi_protocol_vault_performance_fee_gross_of_vote_incentive_fee_base_gap_analyzer": "blind_equal",
    "defi_protocol_vault_performance_fee_hurdle_rate_gap_analyzer": "blind_constant",
    "defi_protocol_vault_performance_fee_management_fee_base_gap_analyzer": "blind_constant",
    "defi_protocol_vault_performance_fee_protocol_revenue_share_base_gap_analyzer": "blind_constant",
    "defi_protocol_vault_performance_fee_subscription_timing_equalization_gap_analyzer": "blind_constant",
    "defi_protocol_vault_performance_fee_unrealized_gain_clawback_gap_analyzer": "blind_constant",
    "defi_protocol_vault_performance_fee_volatility_tax_analyzer": "blind_constant",
    "defi_protocol_vault_price_return_contamination_analyzer": "blind_constant",
    "defi_protocol_vault_range_uptime_fee_realization_analyzer": "blind_constant",
    "defi_protocol_vault_reward_autosell_slippage_analyzer": "blind_constant",
    "defi_protocol_vault_reward_emission_expiry_cliff_analyzer": "blind_constant",
    "defi_protocol_vault_reward_lock_discount_analyzer": "blind_constant",
    "defi_protocol_vault_reward_sell_pressure_runway_analyzer": "blind_constant",
    "defi_protocol_vault_reward_token_price_exposure_analyzer": "blind_constant",
    "defi_protocol_vault_share_inflation_attack_exposure_analyzer": "blind_constant",
    "defi_protocol_vault_share_price_drawdown_analyzer": "blind_constant",
    "defi_protocol_vault_share_price_premium_analyzer": "blind_constant",
    "defi_protocol_vault_share_price_staleness_analyzer": "blind_constant",
    "defi_protocol_vault_strategy_migration_risk_analyzer": "blind_constant",
    "defi_protocol_vault_trading_fee_apr_volatility_analyzer": "blind_constant",
    "defi_protocol_vault_trailing_window_boost_backdating_analyzer": "blind_constant",
    "defi_protocol_vault_unclaimed_reward_forfeiture_analyzer": "blind_constant",
    "defi_protocol_vault_utilization_peak_headline_revert_analyzer": "blind_constant",
    "defi_protocol_vault_withdrawal_fee_decay_analyzer": "blind_constant",
    "defi_protocol_voting_power_concentration_analyzer": "blind_constant",
    "defi_protocol_yield_source_diversification_scorer": "blind_equal",
    "defi_reward_token_sell_pressure_analyzer": "blind_equal",
    "defi_stablecoin_reserve_quality_scorer": "blind_equal",
    "defi_yield_curve_position_analyzer": "blind_equal",
    "defi_yield_source_diversification_scorer": "blind_equal",
    "defi_yield_source_verifier": "blind_equal",
    "dex_routing_risk_analyzer": "blind_equal",
    "gross_of.defi_protocol_vault_performance_fee_gross_of_bridge_delay_opportunity_cost_analyzer": "blind_equal",
    "gross_of.defi_protocol_vault_performance_fee_gross_of_counterparty_default_risk_premium_analyzer": "blind_equal",
    "gross_of.defi_protocol_vault_performance_fee_gross_of_governance_attack_risk_premium_analyzer": "blind_equal",
    "gross_of.defi_protocol_vault_performance_fee_gross_of_impermanent_loss_premium_analyzer": "blind_equal",
    "gross_of.defi_protocol_vault_performance_fee_gross_of_liquidity_mining_opportunity_cost_analyzer": "blind_equal",
    "gross_of.defi_protocol_vault_performance_fee_gross_of_lst_peg_slippage_analyzer": "blind_equal",
    "gross_of.defi_protocol_vault_performance_fee_gross_of_oracle_manipulation_risk_premium_analyzer": "blind_equal",
    "gross_of.defi_protocol_vault_performance_fee_gross_of_rebalancing_transaction_cost_analyzer": "blind_equal",
    "gross_of.defi_protocol_vault_performance_fee_gross_of_referral_affiliate_fee_analyzer": "blind_equal",
    "gross_of.defi_protocol_vault_performance_fee_gross_of_regulatory_risk_premium_analyzer": "blind_equal",
    "gross_of.defi_protocol_vault_performance_fee_gross_of_token_vesting_unlock_pressure_analyzer": "blind_equal",
    "gross_of.defi_protocol_vault_performance_fee_gross_of_yield_aggregator_platform_fee_analyzer": "blind_equal",
    "gross_of.sequencer_tip": "blind_equal",
    "liquidation_risk_heatmap": "blind_equal",
    "mev_risk_detector": "blind_equal",
    "oracle_price_deviation_detector": "blind_equal",
    "oracle_price_monitor": "blind_equal",
    "protocol_concentration_monitor": "blind_equal",
    "protocol_decay_risk_monitor": "blind_equal",
    "protocol_defi_apy_decomposition_analyzer": "blind_constant",
    "protocol_defi_cross_protocol_contagion_risk_analyzer": "blind_constant",
    "protocol_defi_emission_schedule_risk_analyzer": "blind_constant",
    "protocol_defi_liquidity_mining_dilution_analyzer": "blind_constant",
    "protocol_defi_options_vault_risk_analyzer": "blind_constant",
    "protocol_defi_position_health_monitor": "blind_constant",
    "protocol_defi_protocol_fee_revenue_sustainability_analyzer": "blind_constant",
    "protocol_defi_protocol_insurance_coverage_analyzer": "blind_equal",
    "protocol_defi_protocol_version_migration_risk_analyzer": "blind_constant",
    "protocol_defi_wrapped_asset_backing_verifier": "blind_constant",
    "protocol_defi_yield_bearing_stablecoin_risk_analyzer": "blind_constant",
    "protocol_defi_yield_source_dependency_graph_analyzer": "blind_constant",
    "protocol_defi_yield_strip_pricing_analyzer": "blind_constant",
    "protocol_fee_revenue_sustainability_analyzer": "blind_equal",
    "protocol_fee_structure_analyzer": "blind_equal",
    "protocol_fee_tier_migration_analyzer": "blind_equal",
    "protocol_governance_voter_apathy_analyzer": "blind_equal",
    "protocol_ponzi_risk_screener": "blind_equal",
    "protocol_tvl_concentration_analyzer": "blind_constant",
    "protocol_version_risk_analyzer": "blind_equal",
    "protocol_version_risk_assessor": "blind_constant",
    "protocol_yield_curve_arbitrage_detector": "blind_equal",
    "restaking_risk_analyzer": "blind_constant",
    "staking_apy_ranker": "blind_equal",
    "yield_aggregator_strategy_scorer": "blind_equal",
    "yield_dilution_analyzer": "blind_equal",
    "yield_opportunity_scorer": "blind_equal",
    "yield_source_concentration_risk": "blind_equal",
    "yield_source_diversifier": "blind_equal",
    "yield_spread_zscore_analyzer": "blind_equal",
}

PROTOCOL_BLIND_MODULES: FrozenSet[str] = frozenset(PROTOCOL_BLIND_DETAIL)

# Честные coarse-модули (trio-равные, wide-различающие) — исполняются.
WIDE_OK_MODULES: FrozenSet[str] = frozenset({
    "bridge_risk_assessor",
    "chain_concentration",
    "defi_collateral_health_monitor",
    "defi_protocol_vault_gas_breakeven_analyzer",
    "defi_protocol_vault_management_fee_accrual_analyzer",
    "defi_protocol_vault_performance_fee_gross_of_early_withdrawal_penalty_base_gap_analyzer",
    "defi_protocol_vault_performance_fee_gross_of_exit_slippage_base_gap_analyzer",
    "defi_protocol_vault_performance_fee_gross_of_management_fee_base_gap_analyzer",
    "defi_protocol_vault_performance_fee_gross_of_swap_fee_base_gap_analyzer",
    "defi_protocol_vault_performance_fee_gross_of_withdrawal_fee_base_gap_analyzer",
    "defi_yield_aggregator_fee_analyzer",
    "flash_loan_risk_analyzer",
    "gross_of.defi_protocol_vault_performance_fee_gross_of_basis_risk_premium_analyzer",
    "gross_of.defi_protocol_vault_performance_fee_gross_of_lp_amm_fee_drag_analyzer",
    "lending_market_efficiency_scorer",
    "liquidation_price_monitor",
    "protocol_defi_depeg_contagion_modeler",
    "protocol_defi_vault_fee_structure_breakeven_analyzer",
    "protocol_multi_chain_risk_assessor",
})
