"""
spa_core/academy/content/quiz_bank.py

Server-side quiz bank for Academy modules 0–8.

Structure:
    QUIZ_BANK: dict[int, list[Question]]
    Question: {
        "id": int,             # 1-based, stable within a module
        "text": str,
        "options": list[str],
        "correct_idx": int,    # SERVER-SIDE ONLY — never serialised to a client
        "explanation": str,
    }

Rules / invariants:
  - Each module has >=5 questions (M7 has >=10, and is harder).
  - Passing score: 80% (a question is right iff the chosen option index equals
    correct_idx; the pass threshold uses math.ceil so an 8/10 on M7 passes).
  - ``correct_idx`` and ``explanation`` are SERVER-SIDE ONLY. The only surface
    that ever leaves this process to a client is :func:`get_questions`, which
    strips both keys. Grading happens exclusively via :func:`grade_answers`.
  - M8 (capstone) has NO server-graded quiz: QUIZ_BANK[8] == []. An empty bank
    means :func:`grade_answers` returns score=100.0 / passed=True (auto-pass);
    the M8 gate lives entirely in notes + on-chain verification.

LLM FORBIDDEN in this module (deterministic content + grading, no model calls).
Academy stage 4.
"""

from __future__ import annotations

import math
from typing import Dict, List

# Pass threshold as a fraction of questions answered correctly.
PASS_FRACTION = 0.80


# ── Quiz bank ────────────────────────────────────────────────────────────────
# Every module is a plain list of Question dicts. correct_idx points at the
# 0-based index of the right option. Options are deliberately concrete so the
# distractors are plausible but wrong.

QUIZ_BANK: Dict[int, List[dict]] = {
    0: [
        {'id': 1, 'text': 'Для чего нужен Base Sepolia?', 'text_en': 'What is Base Sepolia for?', 'options': ['Хранить реальные деньги', 'Тренироваться без риска', 'Получить прибыль', 'Майнинг ETH'], 'options_en': ['Storing real money', 'Practising risk-free', 'Making a profit', 'Mining ETH'], 'correct_idx': 1, 'explanation': 'Base Sepolia — это тестовая сеть (testnet). Токены в ней не стоят денег, поэтому на ней безопасно отрабатывать действия перед выходом в mainnet.', 'explanation_en': "Base Sepolia is a testnet. Its tokens are worthless, so it's a safe place to rehearse actions before going to mainnet."},
        {'id': 2, 'text': 'Что такое faucet?', 'text_en': 'What is a faucet?', 'options': ['Кошелёк для хранения ключей', 'Сервис для получения тестового ETH бесплатно', 'Биржа для обмена токенов', 'Смарт-контракт кредитования'], 'options_en': ['A wallet for storing keys', 'A service that gives out test ETH for free', 'An exchange for swapping tokens', 'A lending smart contract'], 'correct_idx': 1, 'explanation': 'Faucet («кран») бесплатно выдаёт небольшое количество тестового ETH, чтобы оплачивать газ в тестовой сети.', 'explanation_en': 'A faucet gives out a small amount of test ETH for free, to pay for gas on the test network.'},
        {'id': 3, 'text': 'Testnet-транзакция подтверждена — это значит...', 'text_en': 'A testnet transaction is confirmed — this means...', 'options': ['Вы заработали реальные деньги', 'Транзакция внесена в блок тестнета, реальных денег нет', 'Средства выведены на биржу', 'Транзакция ждёт ручного одобрения'], 'options_en': ['You earned real money', 'The tx is in a testnet block; no real money moved', 'Funds were sent to an exchange', 'The tx awaits manual approval'], 'correct_idx': 1, 'explanation': 'Подтверждение в тестнете означает лишь включение транзакции в блок тестовой сети; никакой реальной стоимости при этом не перемещается.', 'explanation_en': 'A testnet confirmation only means the tx was included in a test-network block; no real value moves.'},
        {'id': 4, 'text': 'Chain ID сети Base Sepolia?', 'text_en': "What is Base Sepolia's Chain ID?", 'options': ['1', '137', '8453', '84532'], 'options_en': ['1', '137', '8453', '84532'], 'correct_idx': 3, 'explanation': 'Chain ID Base Sepolia — 84532. (1 — Ethereum mainnet, 137 — Polygon, 8453 — Base mainnet.)', 'explanation_en': "Base Sepolia's Chain ID is 84532. (1 = Ethereum mainnet, 137 = Polygon, 8453 = Base mainnet.)"},
        {'id': 5, 'text': 'После практики на тестнете стоит...', 'text_en': 'After practising on the testnet you should...', 'options': ['Сразу вложить крупную сумму в mainnet', 'Повторить те же действия на mainnet с малой суммой', 'Больше никогда не заходить в mainnet', 'Продать тестовый ETH за реальные деньги'], 'options_en': ['Immediately put a large sum into mainnet', 'Repeat the same steps on mainnet with a small amount', 'Never touch mainnet again', 'Sell the test ETH for real money'], 'correct_idx': 1, 'explanation': 'Тестнет — это репетиция. Переходя в mainnet, повторяйте те же шаги с маленькой суммой (учебный лимит ≤ $150), а не сразу с большим капиталом.', 'explanation_en': 'A testnet is a rehearsal. Moving to mainnet, repeat the same steps with a small amount (the ≤ $150 educational limit), not a large capital at once.'},
        {'id': 6, 'text': 'Сайт-«faucet» просит подключить кошелёк и прислать депозит «для разблокировки». Это...', 'text_en': 'A "faucet" site asks you to connect your wallet and send a deposit "to unlock." This is...', 'options': ['Нормально для faucet', 'Признак мошенничества — настоящий faucet просит только адрес', 'Обязательный шаг верификации', 'Способ ускорить выдачу'], 'options_en': ['Normal for a faucet', 'A scam sign — a real faucet asks only for your address', 'A required verification step', 'A way to speed up the payout'], 'correct_idx': 1, 'explanation': 'Настоящий faucet НИЧЕГО не просит, кроме адреса. Просьба «подключить кошелёк» или прислать депозит — типичный фишинг/drainer.', 'explanation_en': 'A real faucet asks for nothing but your address. A request to "connect your wallet" or send a deposit is classic phishing/drainer behaviour.'},
    ],
    1: [
        {'id': 1, 'text': 'Кому можно показывать seed-фразу?', 'text_en': 'Who can you show your seed phrase to?', 'options': ['Службе поддержки протокола', 'Никому и никогда', 'Только доверенному другу', 'Сайту, если он выглядит официально'], 'options_en': ["The protocol's support team", 'No one, ever', 'Only a trusted friend', 'A site if it looks official'], 'correct_idx': 1, 'explanation': 'Seed-фраза — это мастер-ключ ко всем средствам. Её нельзя показывать никому и никогда; настоящая поддержка её не просит.', 'explanation_en': 'The seed phrase is the master key to all funds. No support, service, or course ever needs it — any such request is a scam.'},
        {'id': 2, 'text': 'Что произойдёт, если потерять seed-фразу?', 'text_en': 'What happens if you lose your seed phrase?', 'options': ['Кошелёк восстановится по email', 'Потеряете доступ к кошельку навсегда', 'Средства автоматически вернутся на биржу', 'Ничего, ключ хранится в браузере'], 'options_en': ['The wallet is restored by email', 'You lose access to the wallet forever', 'Funds auto-return to an exchange', 'Nothing, the key is in the browser'], 'correct_idx': 1, 'explanation': 'Без seed-фразы восстановить самостоятельный (non-custodial) кошелёк невозможно — доступ к средствам теряется навсегда.', 'explanation_en': 'The seed is the only backup of your keys. Lose it and there is no recovery path — access is gone permanently.'},
        {'id': 3, 'text': 'SIWE (Sign-In With Ethereum) — это...', 'text_en': 'SIWE (Sign-In With Ethereum) is...', 'options': ['Перевод средств на сайт', 'Стандарт подтверждения владения адресом через подпись', 'Способ раскрыть приватный ключ сервису', 'Комиссия за вход в приложение'], 'options_en': ['Sending funds to a site', 'A standard to prove address ownership via a signature', 'A way to reveal your private key to a service', 'A fee to enter an app'], 'correct_idx': 1, 'explanation': 'SIWE — вход через криптографическую подпись, доказывающую владение адресом. Подпись бесплатна и не двигает средства.', 'explanation_en': 'SIWE proves you own an address by signing a message. It is free and moves no funds — it is not a transaction.'},
        {'id': 4, 'text': 'Бумажный бэкап seed хранить...', 'text_en': 'A paper seed backup should be stored...', 'options': ['В облаке и в переписке для надёжности', 'В физически защищённом месте, не в цифровом виде', 'Скриншотом в галерее телефона', 'В открытом текстовом файле на рабочем столе'], 'options_en': ['In the cloud and in chats for safety', 'In a physically secure place, not digitally', 'As a screenshot in your phone gallery', 'In a plain text file on the desktop'], 'correct_idx': 1, 'explanation': 'Цифровые копии seed (фото, файлы, облако) уязвимы к взлому. Надёжнее — офлайн-бэкап в физически защищённом месте.', 'explanation_en': 'Any digital copy is a theft vector. Store the seed offline, physically.'},
        {'id': 5, 'text': 'Что такое hardware wallet?', 'text_en': 'What is a hardware wallet?', 'options': ['Онлайн-биржа с высокой доходностью', 'Устройство, хранящее ключи оффлайн', 'Расширение браузера с паролем', 'Резервная копия seed в облаке'], 'options_en': ['An online exchange with high yield', 'A device that keeps keys offline', 'A browser extension with a password', 'A cloud backup of the seed'], 'correct_idx': 1, 'explanation': 'Аппаратный кошелёк хранит приватные ключи на изолированном устройстве, недоступном заражённому компьютеру.', 'explanation_en': 'A hardware wallet holds keys on an isolated device, protecting them from an infected computer.'},
        {'id': 6, 'text': 'Из одной seed-фразы можно получить...', 'text_en': 'From one seed phrase you can derive...', 'options': ['Только один адрес', 'Много адресов (HD-деривация)', 'Только приватный ключ биржи', 'Ничего без пароля'], 'options_en': ['Only one address', 'Many addresses (HD derivation)', "Only an exchange's private key", 'Nothing without a password'], 'correct_idx': 1, 'explanation': 'Seed детерминированно порождает приватный ключ и множество адресов — поэтому seed = доступ ко ВСЕМ вашим адресам.', 'explanation_en': 'A seed deterministically derives a private key and many addresses — so the seed is access to ALL your addresses.'},
    ],
    2: [
        {'id': 1, 'text': 'Почему Base дешевле Ethereum mainnet?', 'text_en': 'Why is Base cheaper than Ethereum mainnet?', 'options': ['Base — L2, батчует транзакции', 'Base не использует блокчейн', 'Base субсидирует газ из своего кармана', 'На Base нет комиссий вообще'], 'options_en': ['Base is an L2 that batches transactions', "Base doesn't use a blockchain", 'Base subsidises gas from its own pocket', 'Base has no fees at all'], 'correct_idx': 0, 'explanation': 'Base — это L2 (rollup): он собирает много транзакций в пакет и публикует их в L1 вместе, деля стоимость → комиссии ниже.', 'explanation_en': "Base is an L2 rollup: it bundles many txs into one L1 post and splits the cost, so fees are a fraction of mainnet's."},
        {'id': 2, 'text': 'Gas — это...', 'text_en': 'Gas is...', 'options': ['Токен для голосования', 'Вычислительная стоимость транзакции в ETH', 'Комиссия биржи за вывод', 'Проценты по депозиту'], 'options_en': ['A governance token', 'The computational cost of a transaction, paid in ETH', 'An exchange withdrawal fee', 'Interest on a deposit'], 'correct_idx': 1, 'explanation': 'Газ — мера вычислительной работы транзакции; оплачивается в ETH и достаётся тем, кто обрабатывает сеть.', 'explanation_en': 'Gas is the compute cost of a tx, paid in ETH — every on-chain action needs some.'},
        {'id': 3, 'text': 'Если газ закончился до завершения транзакции...', 'text_en': 'If gas runs out before a transaction finishes...', 'options': ['Транзакция завершится позже сама', 'Транзакция откатывается, ETH за газ всё равно списывается', 'ETH за газ полностью возвращается', 'Сеть доплатит недостающий газ'], 'options_en': ['It finishes later on its own', 'It reverts, but the gas spent is still charged', 'The gas is fully refunded', 'The network tops up the missing gas'], 'correct_idx': 1, 'explanation': 'При нехватке газа транзакция откатывается (revert), но потраченный на вычисления газ не возвращается.', 'explanation_en': 'A revert rolls back the state change, but the gas already consumed is not refunded.'},
        {'id': 4, 'text': 'Base chainId?', 'text_en': "Base's chainId?", 'options': ['1', '8453', '137', '42161'], 'options_en': ['1', '8453', '137', '42161'], 'correct_idx': 1, 'explanation': 'Chain ID Base mainnet — 8453. (1 — Ethereum, 137 — Polygon, 42161 — Arbitrum.)', 'explanation_en': "Base mainnet's Chain ID is 8453."},
        {'id': 5, 'text': 'ETH на газ нужен для...', 'text_en': 'ETH for gas is needed to...', 'options': ['Только для покупки NFT', 'Оплаты любых транзакций на Base, включая transfer стейблов', 'Хранения на бирже', 'Начисления процентов в Aave'], 'options_en': ['Only buy NFTs', 'Pay for any transaction on Base, including stablecoin transfers', 'Store on an exchange', 'Accrue interest in Aave'], 'correct_idx': 1, 'explanation': 'Даже перевод стейблкоина — это транзакция, а значит требует немного ETH на газ. Держите ETH-подушку на учебном кошельке (лимит ≤ $150).', 'explanation_en': 'Every on-chain action needs ETH for gas — even sending a stablecoin. No ETH, no actions.'},
        {'id': 6, 'text': 'У вас есть ETH на Ethereum, но нужно оплатить газ на Base. Что делать?', 'text_en': 'You have ETH on Ethereum but need to pay gas on Base. What do you do?', 'options': ['ETH на Ethereum оплатит газ на Base напрямую', 'Нужен ETH именно в сети Base (перенести через мост или завести туда)', 'Газ на Base платится в USDC', 'Base не требует газа'], 'options_en': ['ETH on Ethereum pays Base gas directly', 'You need ETH on the Base network itself (bridge it or fund it there)', 'Base gas is paid in USDC', 'Base needs no gas'], 'correct_idx': 1, 'explanation': 'Газ нужен в той же сети, где действуешь. ETH на Ethereum не оплатит газ на Base — активы между сетями переносит мост (bridge), но это отдельный риск.', 'explanation_en': "Gas is needed on the network you act on. ETH on Ethereum won't pay Base gas — a bridge moves assets between networks, but that is a separate risk."},
    ],
    3: [
        {'id': 1, 'text': 'Pending транзакция означает...', 'text_en': 'A pending transaction means...', 'options': ['Транзакция отклонена сетью', 'Ожидает включения в блок', 'Средства уже зачислены', 'Требуется повторная подпись'], 'options_en': ['The network rejected it', "It's waiting to be included in a block", 'Funds are already credited', 'It needs re-signing'], 'correct_idx': 1, 'explanation': 'Pending — транзакция отправлена в mempool и ждёт включения в блок; она ещё не финальна.', 'explanation_en': 'Pending means the tx is submitted and waiting for validators to include it in a block.'},
        {'id': 2, 'text': 'После скольких подтверждений транзакция считается финальной?', 'text_en': 'After how many confirmations is a tx reasonably final?', 'options': ['Достаточно 0 подтверждений', '≥5 подтверждений для разумной уверенности', 'Ровно 1 подтверждение всегда достаточно', 'Не менее 1000 подтверждений'], 'options_en': ['0 is enough', '~5 confirmations for reasonable certainty', 'Exactly 1 is always enough', 'At least 1000'], 'correct_idx': 1, 'explanation': 'Одно подтверждение уже почти финально на L2, но для разумной уверенности принято дождаться нескольких (≥5) блоков.', 'explanation_en': 'One confirmation on an L2 is nearly final, but for larger amounts waiting several blocks adds certainty.'},
        {'id': 3, 'text': 'Что такое tx hash?', 'text_en': 'What is a tx hash?', 'options': ['Пароль от кошелька', 'Уникальный ID транзакции в блокчейне', 'Адрес получателя', 'Сумма комиссии'], 'options_en': ['Your wallet password', 'A unique transaction ID on the blockchain', 'The recipient address', 'The fee amount'], 'correct_idx': 1, 'explanation': 'Tx hash — уникальный идентификатор транзакции; по нему её можно найти и проверить в block explorer.', 'explanation_en': "A tx hash is a transaction's unique public identifier — you look it up in an explorer."},
        {'id': 4, 'text': 'Как проверить статус транзакции?', 'text_en': "How do you check a transaction's status?", 'options': ['Позвонить в поддержку сети', 'По tx hash в block explorer (basescan.org)', 'Переслать seed-фразу боту', 'Подождать письмо на email'], 'options_en': ['Call network support', 'By tx hash in a block explorer (basescan.org)', 'Send your seed phrase to a bot', 'Wait for an email'], 'correct_idx': 1, 'explanation': 'Статус любой транзакции публично виден в block explorer по её tx hash — например, на basescan.org.', 'explanation_en': 'Paste the tx hash into a block explorer to see status, amount, and parties.'},
        {'id': 5, 'text': 'Transfer стейбла не прошёл — что проверить?', 'text_en': 'A stablecoin transfer failed — what to check?', 'options': ['Скорость интернета', 'Баланс газа, одобрение, корректность адреса', 'Курс доллара', 'Погоду в сети'], 'options_en': ['Your internet speed', 'Gas balance, approval, and the address is correct', 'The dollar exchange rate', 'The network weather'], 'correct_idx': 1, 'explanation': 'Типичные причины неуспеха: нет ETH на газ, отсутствует нужный approval, неверный адрес получателя.', 'explanation_en': 'Common causes: no ETH for gas, a missing approval, or a wrong recipient address.'},
        {'id': 6, 'text': 'Nonce у адреса — это...', 'text_en': "An address's nonce is...", 'options': ['Случайное число для шифрования', 'Счётчик его транзакций по порядку', 'Комиссия сети', 'Адрес получателя'], 'options_en': ['A random number for encryption', 'An in-order counter of its transactions', 'A network fee', 'The recipient address'], 'correct_idx': 1, 'explanation': 'Nonce не даёт исполнить одну транзакцию дважды и задаёт порядок; тот же nonce используют для speed-up/cancel.', 'explanation_en': 'The nonce prevents a tx from executing twice and sets ordering; the same nonce is used to speed-up/cancel.'},
    ],
    4: [
        {'id': 1, 'text': 'Approval — это...', 'text_en': 'An approval is...', 'options': ['Перевод токенов на биржу', 'Разрешение контракту тратить ваши токены', 'Подтверждение личности', 'Начисление процентов'], 'options_en': ['Sending tokens to an exchange', 'Permission for a contract to spend your tokens', 'Identity verification', 'Interest accrual'], 'correct_idx': 1, 'explanation': 'Approval даёт смарт-контракту право списывать ваши токены до указанного лимита — сам по себе он не переводит средства.', 'explanation_en': 'An approval lets a contract spend your tokens up to a limit — it moves no funds by itself.'},
        {'id': 2, 'text': 'Unlimited approval опасен, потому что...', 'text_en': 'Unlimited approval is dangerous because...', 'options': ['Он замедляет транзакции', 'Взломанный контракт может вывести все токены', 'Он повышает комиссию сети', 'Он блокирует ваш кошелёк'], 'options_en': ['It slows transactions', 'A compromised contract can drain all tokens', 'It raises the network fee', 'It locks your wallet'], 'correct_idx': 1, 'explanation': 'Безлимитный approval позволяет контракту (или его взломщику) списать весь баланс токена. Одобряйте только нужную сумму.', 'explanation_en': "With unlimited approval, a hacked contract can pull your entire token balance. Approve only what's needed."},
        {'id': 3, 'text': 'Revoke — это...', 'text_en': 'Revoke is...', 'options': ['Повторный депозит', 'Отзыв разрешения (approval с value=0)', 'Смена сети', 'Восстановление seed-фразы'], 'options_en': ['A repeat deposit', 'Cancelling an approval (approve with value 0)', 'Switching networks', 'Restoring a seed phrase'], 'correct_idx': 1, 'explanation': 'Revoke — это установка approval в 0, то есть отзыв ранее выданного контракту разрешения тратить токены.', 'explanation_en': "Revoking sets the allowance to 0, closing a contract's access to your tokens."},
        {'id': 4, 'text': 'Разница между подписью (sign) и транзакцией?', 'text_en': 'Difference between a signature (sign) and a transaction?', 'options': ['Подпись дороже транзакции', 'Подпись бесплатна, транзакция списывает газ', 'Обе всегда двигают средства', 'Транзакция бесплатна, подпись платная'], 'options_en': ['A signature costs more', 'A signature is free; a transaction spends gas', 'Both always move funds', 'A transaction is free, a signature is paid'], 'correct_idx': 1, 'explanation': 'Подпись сообщения не отправляется в сеть и бесплатна; транзакция меняет состояние блокчейна и требует газа.', 'explanation_en': 'A signature authorizes without gas; a transaction changes on-chain state and costs gas.'},
        {'id': 5, 'text': 'Перед depositом в протокол нужно...', 'text_en': 'Before depositing into a protocol you need to...', 'options': ['Отправить seed-фразу протоколу', 'Сделать Approval на нужную сумму', 'Отключить кошелёк', 'Купить токен протокола'], 'options_en': ['Send your seed phrase to the protocol', 'Approve the required amount', 'Disconnect the wallet', "Buy the protocol's token"], 'correct_idx': 1, 'explanation': 'Чтобы контракт мог принять ваш токен в депозит, ему сперва нужен approval на конкретную сумму.', 'explanation_en': 'A deposit usually needs a prior approval for the amount the protocol will pull.'},
        {'id': 6, 'text': 'Что удобно использовать, чтобы проверить и отозвать старые allowance?', 'text_en': "What's handy for reviewing and revoking old allowances?", 'options': ['Личный кабинет биржи', 'revoke.cash', 'Почтовый клиент', 'Faucet'], 'options_en': ['An exchange dashboard', 'revoke.cash', 'An email client', 'A faucet'], 'correct_idx': 1, 'explanation': 'revoke.cash показывает активные разрешения по адресу и даёт их отозвать. Старые approvals стоит периодически чистить.', 'explanation_en': 'revoke.cash lists active allowances for an address and lets you revoke them. Clean up old approvals periodically.'},
    ],
    5: [
        {'id': 1, 'text': 'Что происходит при Supply в Aave?', 'text_en': 'What happens on Supply to Aave?', 'options': ['Токены сгорают', 'Токены идут в пул, вы получаете aToken (процентный)', 'Токены уходят на биржу', 'Открывается заём под залог'], 'options_en': ['The tokens are burned', 'Tokens go to the pool; you get an interest-bearing aToken', 'Tokens go to an exchange', 'A collateralised loan opens'], 'correct_idx': 1, 'explanation': 'Supply вносит ваши токены в пул ликвидности; взамен вы получаете aToken, который автоматически растёт с процентами.', 'explanation_en': 'Supply puts tokens in the pool; you receive an aToken receipt whose balance grows with interest.'},
        {'id': 2, 'text': 'aUSDC — это...', 'text_en': 'aUSDC is...', 'options': ['Отдельная монета-мем', 'Токен, подтверждающий депозит, автоматически начисляет проценты', 'Долговая расписка биржи', 'Тестовый токен без ценности'], 'options_en': ['A separate meme coin', 'A token proving your deposit that auto-accrues interest', 'An exchange IOU', 'A worthless test token'], 'correct_idx': 1, 'explanation': 'aUSDC — процентный токен-квитанция депозита USDC в Aave; его баланс сам растёт по мере начисления процентов.', 'explanation_en': 'aUSDC is your deposit receipt; its balance increases as interest accrues.'},
        {'id': 3, 'text': 'Перед подтверждением Supply надо проверить...', 'text_en': 'Before confirming Supply, verify...', 'options': ['Курс биткоина', 'Адрес контракта, сумму, газ', 'Погоду', 'Номер телефона поддержки'], 'options_en': ['The bitcoin price', 'The contract address, amount, and gas', 'The weather', 'The support phone number'], 'correct_idx': 1, 'explanation': 'Всегда сверяйте адрес контракта (официальный ли), вносимую сумму и наличие ETH на газ перед подписью.', 'explanation_en': 'Always verify the official contract address, the amount, and that you have ETH for gas.'},
        {'id': 4, 'text': 'Liquidation в Aave происходит при...', 'text_en': 'Liquidation in Aave happens when...', 'options': ['Любом депозите', 'Падении стоимости залога ниже порога (для stablecoin-only — редко)', 'Выводе средств', 'Начислении процентов'], 'options_en': ['Any deposit', 'Collateral value drops below a threshold (rare for stablecoin-only)', 'You withdraw', 'Interest accrues'], 'correct_idx': 1, 'explanation': 'Ликвидация грозит заёмщикам, чей залог упал ниже порога. При чисто стейблкоиновой позиции без займа это крайне редко.', 'explanation_en': 'Liquidation threatens borrowers whose collateral falls below a threshold. Supply-only, no borrow: nothing to liquidate.'},
        {'id': 5, 'text': 'APY в Aave означает...', 'text_en': 'APY in Aave means...', 'options': ['Разовую комиссию', 'Годовую доходность с учётом сложных процентов', 'Налог на прибыль', 'Цену газа'], 'options_en': ['A one-time fee', 'The annual yield with compounding', 'A profit tax', 'The gas price'], 'correct_idx': 1, 'explanation': 'APY — годовая доходность с учётом капитализации (сложных процентов). Она плавает вместе со ставками пула.', 'explanation_en': 'APY is the annualised yield with compounding; it floats with pool utilization.'},
        {'id': 6, 'text': 'Откуда берётся доход (APY) вкладчика в Aave?', 'text_en': "Where does a supplier's yield (APY) in Aave come from?", 'options': ['Печатается протоколом из воздуха', 'Из процентов, которые платят заёмщики', 'Из комиссий за газ', 'Из airdrop-ов'], 'options_en': ['Printed by the protocol from thin air', 'From the interest borrowers pay', 'From gas fees', 'From airdrops'], 'correct_idx': 1, 'explanation': 'Заёмщики платят процент за средства из пула; он распределяется вкладчикам. APY плавает с utilization.', 'explanation_en': "Borrowers pay interest on pooled funds; it's distributed to suppliers. APY floats with utilization."},
    ],
    6: [
        {'id': 1, 'text': 'Withdraw возвращает...', 'text_en': 'Withdraw returns...', 'options': ['Только проценты', 'Первоначальный депозит + накопленные проценты', 'Половину депозита', 'Токен протокола вместо стейбла'], 'options_en': ['Only the interest', 'The original deposit plus accrued interest', 'Half the deposit', 'The protocol token instead of the stablecoin'], 'correct_idx': 1, 'explanation': 'Withdraw возвращает исходный депозит вместе с процентами, накопившимися за время удержания.', 'explanation_en': 'Withdraw returns your principal plus the interest accrued while held.'},
        {'id': 2, 'text': 'aToken после Withdraw...', 'text_en': 'After Withdraw, the aToken...', 'options': ['Остаётся на кошельке навсегда', 'Сжигается (burn) автоматически', 'Переводится другому пользователю', 'Превращается в NFT'], 'options_en': ['Stays in your wallet forever', 'Is automatically burned', 'Is sent to another user', 'Becomes an NFT'], 'correct_idx': 1, 'explanation': 'При выводе соответствующий aToken сжигается — он был лишь квитанцией на депозит.', 'explanation_en': 'The aToken is burned on withdrawal — the receipt is redeemed for the underlying asset.'},
        {'id': 3, 'text': 'Почему важно мониторить позицию?', 'text_en': 'Why is it important to monitor a position?', 'options': ['Чтобы платить меньше налогов', 'Чтобы реагировать на изменение APY или рисков протокола', 'Чтобы увеличить газ', 'Это не важно'], 'options_en': ['To pay less tax', 'To react to changing APY or protocol risk', 'To increase gas', "It isn't important"], 'correct_idx': 1, 'explanation': 'Ставки и риски протокола меняются. Мониторинг позволяет вовремя выйти, если условия ухудшились.', 'explanation_en': 'Rates, utilization, and protocol risk change over time; monitoring lets you act on a kill-rule.'},
        {'id': 4, 'text': 'Что проверить перед крупным выводом?', 'text_en': 'What to check before a large withdrawal?', 'options': ['Курс акций', 'Доступную ликвидность в пуле', 'Скорость интернета', 'Баланс на бирже'], 'options_en': ['The stock market', 'Available liquidity in the pool', 'Internet speed', 'An exchange balance'], 'correct_idx': 1, 'explanation': 'Если пул временно исчерпан заёмщиками, крупный вывод может быть недоступен сразу — проверяйте доступную ликвидность.', 'explanation_en': 'At very high utilization the free part of the pool may be insufficient for an instant large withdrawal.'},
        {'id': 5, 'text': 'Kill-rule — это...', 'text_en': 'A kill-rule is...', 'options': ['Комиссия за вывод', 'Заранее определённое условие для немедленного выхода', 'Максимальный размер депозита', 'Ставка налога'], 'options_en': ['A withdrawal fee', 'A pre-defined condition to exit immediately', 'A maximum deposit size', 'A tax rate'], 'correct_idx': 1, 'explanation': 'Kill-rule — заранее прописанное правило, при срабатывании которого вы немедленно выходите из позиции без раздумий.', 'explanation_en': 'A kill-rule is a rule you set before entering, executed mechanically to exit without hope or emotion.'},
        {'id': 6, 'text': 'Пул на ~100% utilization. Ваш крупный вывод...', 'text_en': 'A pool is ~100% utilized. Your large withdrawal...', 'options': ['Пройдёт мгновенно в любом случае', 'Может быть временно недоступен, пока не вернётся ликвидность', 'Навсегда заблокирован', 'Спишет двойную комиссию'], 'options_en': ['Goes through instantly regardless', 'May be temporarily unavailable until liquidity returns', 'Is locked forever', 'Charges a double fee'], 'correct_idx': 1, 'explanation': 'Вывод возможен из свободной части пула. При ~100% занятости крупный вывод ждёт возврата средств; частичный обычно проходит.', 'explanation_en': 'Withdrawals come from the free part of the pool. At ~100% utilization a large one waits for repayments; a partial usually still works.'},
    ],
    7: [
        {'id': 1, 'text': 'Фишинговый сайт — как распознать?', 'text_en': 'How do you spot a phishing site?', 'options': ['По красивому дизайну', 'Проверить точный URL, SSL, источник ссылки', 'По обещанию высокой доходности', 'Никак, все сайты безопасны'], 'options_en': ['By pretty design', 'Check the exact URL, SSL, and link source', 'By a promise of high yield', "You can't, all sites are safe"], 'correct_idx': 1, 'explanation': 'Фишинг маскируется под настоящий сайт. Сверяйте точный URL по символам, наличие HTTPS и откуда пришла ссылка.', 'explanation_en': 'Verify the exact URL, the HTTPS lock, and where the link came from. Design proves nothing.'},
        {'id': 2, 'text': 'Drainer-подпись — это...', 'text_en': 'A drainer signature is...', 'options': ['Подпись для входа в аккаунт', 'Вредоносный approve/permit, отдающий все токены злоумышленнику', 'Обычная транзакция перевода', 'Подпись для получения airdrop'], 'options_en': ['A login signature', 'A malicious approve/permit that hands all tokens to an attacker', 'A normal transfer transaction', 'A signature to receive an airdrop'], 'correct_idx': 1, 'explanation': 'Drainer выманивает подпись approve/permit, которая даёт атакующему право вывести все ваши токены.', 'explanation_en': 'A drainer signature is a malicious approve/permit that gives an attacker access to drain your tokens.'},
        {'id': 3, 'text': 'Подписал permit — как отозвать?', 'text_en': 'You signed a permit — how to revoke?', 'options': ['Никак, ничего не поделать', 'Revoke через revoke.cash или etherscan; если уже исполнен — невозможно', 'Сменить пароль от email', 'Перезагрузить кошелёк'], 'options_en': ['Nothing can be done', 'Revoke via revoke.cash or an explorer; if already executed, impossible', 'Change your email password', 'Restart the wallet'], 'correct_idx': 1, 'explanation': 'Пока permit не исполнен, отзовите разрешение (revoke.cash / etherscan). Если атакующий уже исполнил его — отмена невозможна.', 'explanation_en': "If the permit isn't executed yet, revoke the allowance. Once executed, it can't be undone."},
        {'id': 4, 'text': 'Permit (EIP-2612) опаснее Approval, потому что...', 'text_en': 'Permit (EIP-2612) is more dangerous than Approval because...', 'options': ['Он требует больше газа', 'Не требует газа от жертвы, подпись может быть использована офлайн', 'Он виден в block explorer', 'Он работает только на тестнете'], 'options_en': ['It needs more gas', 'It needs no gas from the victim and can be used off-chain later', 'It shows in a block explorer', 'It only works on testnet'], 'correct_idx': 1, 'explanation': 'Permit — это подпись, не транзакция: жертва не платит газ и не видит её в истории, а атакующий может предъявить её позже.', 'explanation_en': "A permit is a gasless signature the victim doesn't see in history; the attacker presents it later."},
        {'id': 5, 'text': 'Поддельный токен airdrop — правило?', 'text_en': 'A fake airdrop token — the rule?', 'options': ['Быстро продать через любой dex', 'Не взаимодействовать, не продавать через неизвестные dex', 'Одобрить его контракту', 'Отправить другу'], 'options_en': ['Sell it fast on any dex', "Don't interact, don't sell via unknown dexes", 'Approve it to a contract', 'Send it to a friend'], 'correct_idx': 1, 'explanation': 'Неизвестные «подарочные» токены — приманка: их продажа ведёт на вредоносный контракт. Не взаимодействуйте с ними.', 'explanation_en': 'Interacting with a scam token (approve/sell via its dex) can trigger a drain. Ignore it.'},
        {'id': 6, 'text': "Если нажал 'Connect' на фишинге — достаточно ли disconnect?", 'text_en': "If you clicked 'Connect' on a phishing site, is disconnect enough?", 'options': ['Да, disconnect всё решает', 'Нет — проверить активные approvals и при подозрении перевести средства', 'Достаточно закрыть вкладку', 'Нужно только сменить сеть'], 'options_en': ['Yes, disconnect fixes everything', 'No — check active approvals and move funds if suspicious', 'Just close the tab', 'Only switch networks'], 'correct_idx': 1, 'explanation': 'Само подключение не крадёт средства, но если вы что-то подписали — disconnect не отменит approval. Проверьте разрешения и при риске выведите средства.', 'explanation_en': "Connecting alone doesn't move funds, but a signed approval might. Check allowances and move funds if in doubt."},
        {'id': 7, 'text': 'Social engineering — как подтвердить подлинность сайта?', 'text_en': "Social engineering — how to confirm a site's authenticity?", 'options': ['Довериться ссылке из чата поддержки', 'Bookmarks из официальных источников, не по ссылкам из chat', 'Искать сайт в рекламе поисковика', 'Спросить в комментариях'], 'options_en': ['Trust a link from a support chat', 'Use bookmarks from official sources, not chat links', 'Search for it in a search ad', 'Ask in the comments'], 'correct_idx': 1, 'explanation': 'Ссылки из чатов, DM и рекламы — частый вектор фишинга. Заходите по сохранённым закладкам из официальных источников.', 'explanation_en': 'Arrive via your own saved bookmarks, never links from chats, ads, or DMs.'},
        {'id': 8, 'text': 'Транзакция застряла в pending — правильное действие?', 'text_en': 'A transaction is stuck in pending — the right action?', 'options': ['Отправить ещё десять таких же', 'Speed-up с тем же nonce или cancel (замена нулевой суммой)', 'Переслать seed-фразу в поддержку', 'Просто ждать неделю'], 'options_en': ['Send ten more like it', 'Speed-up with the same nonce, or cancel (zero-value replacement)', 'Send your seed to support', 'Just wait a week'], 'correct_idx': 1, 'explanation': 'Застрявшую транзакцию можно ускорить (speed-up, тот же nonce, выше комиссия) или отменить заменяющей нулевой транзакцией.', 'explanation_en': "Resend with the same nonce and a higher fee to speed up or cancel it — don't spam new txs."},
        {'id': 9, 'text': 'При каждой подписи проверить...', 'text_en': 'On every signature, verify...', 'options': ['Только сумму', 'Адрес контракта, что именно подписываешь, наличие в whitelist', 'Цвет кнопки', 'Скорость интернета'], 'options_en': ['Only the amount', "The contract address, what you're signing, and it's whitelisted", 'The button colour', 'Internet speed'], 'correct_idx': 1, 'explanation': 'Перед подписью сверяйте адрес контракта, суть операции и то, что домен/контракт есть в вашем whitelist доверенных.', 'explanation_en': 'Read what you sign and who gets spender access — every time.'},
        {'id': 10, 'text': 'Hardware wallet защищает от...', 'text_en': 'A hardware wallet protects against...', 'options': ['Любых ошибок пользователя', 'Кражи ключей с заражённого компьютера, но не от фишинговых подписей', 'Роста комиссий сети', 'Падения курса токена'], 'options_en': ['Any user error', 'Key theft from an infected computer, but not phishing signatures', 'Rising network fees', 'A falling token price'], 'correct_idx': 1, 'explanation': 'Аппаратный кошелёк изолирует ключи от заражённого ПК, но если вы сами подпишете вредоносный permit — он это исполнит.', 'explanation_en': 'It isolates keys from a compromised PC, but you can still sign a malicious message — you must read.'},
    ],
    8: [
        {"id": 1, "text": "Капстоун: в каком порядке идёт полный цикл на Base?", "text_en": "Capstone: what is the correct order of the full loop on Base?", "options": ["Supply → Approval → Tx → Withdraw → Monitor", "Wallet → Network → Tx → Approval → Supply → Monitor → Withdraw", "Approval → Supply → Wallet → Network → Withdraw", "Network → Withdraw → Supply → Approval → Wallet"], "options_en": ["Supply → Approval → Tx → Withdraw → Monitor", "Wallet → Network → Tx → Approval → Supply → Monitor → Withdraw", "Approval → Supply → Wallet → Network → Withdraw", "Network → Withdraw → Supply → Approval → Wallet"], "correct_idx": 1, "explanation": "Сначала контролируешь ключи (wallet) и сеть, потом транзакция, разрешение (approval), внесение (supply), мониторинг и вывод. Порядок = цепочка риска.", "explanation_en": "First own the keys (wallet) and network, then the tx, the approval, the supply, then monitor and withdraw. The order IS the chain of risk."},
        {"id": 2, "text": "Зачем в капстоуне жёсткий лимит ≤ $150?", "text_en": "Why the hard ≤ $150 limit in the capstone?", "options": ["Чтобы больше заработать", "Это учебный предел: доказать владение механикой и дисциплиной при риске, который не жалко потерять", "Так требует протокол Aave", "Лимит ни на что не влияет"], "options_en": ["To earn more", "It's an educational cap: prove you own the mechanics AND the discipline at a loss you can afford", "Aave requires it", "The limit doesn't matter"], "correct_idx": 1, "explanation": "Смысл капстоуна — не доход, а доказательство контроля. Малый лимит превращает ошибку в дешёвый урок, а не в катастрофу.", "explanation_en": "The capstone proves control, not yield. A small cap turns a mistake into a cheap lesson, not a disaster."},
        {"id": 3, "text": "«Цепочка риска настолько крепка, насколько крепко её слабое звено» — что это значит на практике?", "text_en": "\"A chain of risk is only as strong as its weakest link\" — what does this mean in practice?", "options": ["Достаточно защитить один шаг", "Одна ошибка (слитый ключ, слепой approval, не то сеть) обнуляет всю остальную аккуратность", "Звенья не связаны между собой", "Слабое звено — это всегда доходность"], "options_en": ["Securing one step is enough", "One failure (leaked key, blind approval, wrong network) cancels out all your other care", "The links are independent", "The weakest link is always the yield"], "correct_idx": 1, "explanation": "Каждый модуль — звено: ключи, сеть, tx, approval, supply, мониторинг, вывод. Провал любого сводит на нет остальные.", "explanation_en": "Each module is a link: keys, network, tx, approval, supply, monitor, withdraw. Failing any one nullifies the rest."},
        {"id": 4, "text": "Что важнее подтверждает капстоун — «механику» или «дисциплину»?", "text_en": "What does the capstone prove — the \"mechanics\" or the \"discipline\"?", "options": ["Только механику (клики в интерфейсе)", "И то, и другое: ты умеешь выполнить шаги И держать лимиты/правила под давлением", "Только скорость", "Только размер позиции"], "options_en": ["Only mechanics (clicking the UI)", "Both: you can execute the steps AND hold limits/rules under pressure", "Only speed", "Only position size"], "correct_idx": 1, "explanation": "Механика без дисциплины опасна. Капстоун доказывает оба: ты и делаешь правильно, и не нарушаешь свои же правила ради «чуть больше».", "explanation_en": "Mechanics without discipline is dangerous. The capstone proves both: you execute correctly AND you don't break your own rules for 'a bit more'."},
        {"id": 5, "text": "Перед Supply ты даёшь Approval. Какой риск нужно контролировать именно здесь?", "text_en": "Before Supply you grant an Approval. What risk must you control here?", "options": ["Никакого, approval безопасен всегда", "Неограниченный (infinite) approval неизвестному контракту — ограничивай сумму и проверяй адрес контракта", "Approval нельзя отозвать", "Approval меняет твою сеть"], "options_en": ["None, approval is always safe", "An infinite approval to an unknown contract — cap the amount and verify the contract address", "Approval can't be revoked", "Approval changes your network"], "correct_idx": 1, "explanation": "Approval — это разрешение тратить твои токены. Давай минимально нужную сумму проверенному контракту; лишние infinite-approvals потом отзывай.", "explanation_en": "An approval lets a contract spend your tokens. Grant the minimum to a verified contract; revoke stray infinite approvals later."},
        {"id": 6, "text": "После Supply — что значит шаг Monitor в капстоуне?", "text_en": "After Supply — what does the Monitor step mean in the capstone?", "options": ["Забыть про позицию до вывода", "Следить за состоянием: ставка/здоровье позиции, сеть, что средства реально твои и выводимы", "Смотреть только на цену токена", "Мониторинг не нужен на малых суммах"], "options_en": ["Forget the position until withdrawal", "Track the state: rate/position health, the network, and that funds are truly yours and withdrawable", "Watch only the token price", "No monitoring needed for small amounts"], "correct_idx": 1, "explanation": "Мониторинг = проверять, что позиция здорова и выводима. Дисциплина не заканчивается на внесении средств.", "explanation_en": "Monitoring means checking the position is healthy and withdrawable. Discipline doesn't end at deposit."},
        {"id": 7, "text": "Почему шаг Withdraw обязателен, чтобы капстоун считался пройденным?", "text_en": "Why is the Withdraw step required for the capstone to count as complete?", "options": ["Чтобы зафиксировать прибыль", "Доказать, что ты можешь ВЫЙТИ: средства реально твои и извлекаемы — не только внесены", "Withdraw нужен только при убытке", "Это формальность без смысла"], "options_en": ["To lock in profit", "To prove you can EXIT: funds are truly yours and retrievable — not just deposited", "Withdraw only matters on a loss", "It's a meaningless formality"], "correct_idx": 1, "explanation": "Полный цикл = вход И выход. Пока не вывел — не доказал контроль над средствами. Exit — часть безопасности.", "explanation_en": "A full loop is entry AND exit. Until you withdraw, you haven't proven control of the funds. Exit is part of safety."},
        {"id": 8, "text": "Что подтверждает завершённый капстоун — и что он НЕ подтверждает?", "text_en": "What does a completed capstone prove — and what does it NOT prove?", "options": ["Что ты профессиональный трейдер и готов к большим суммам", "Что ты владеешь безопасным полным циклом на малом риске; он НЕ обещает доход и не снимает лимиты", "Что можно отключить дисциплину", "Что риск теперь нулевой"], "options_en": ["That you're a pro trader ready for big size", "That you own the safe full loop at small risk; it does NOT promise yield or remove limits", "That you can switch off discipline", "That risk is now zero"], "correct_idx": 1, "explanation": "Капстоун = сертификат владения механикой и дисциплиной на учебном риске. Доход, масштаб и снятие лимитов — это отдельные, более поздние решения.", "explanation_en": "The capstone certifies you own the mechanics and discipline at educational risk. Yield, scale, and lifting limits are separate, later decisions."},
    ],
}


# ── Public helpers ───────────────────────────────────────────────────────────


def _bank_for(lesson_id: int) -> List[dict]:
    """Return the question list for *lesson_id* or raise KeyError."""
    if lesson_id not in QUIZ_BANK:
        raise KeyError(f"no quiz bank for lesson_id={lesson_id!r}")
    return QUIZ_BANK[lesson_id]


def get_questions(lesson_id: int, lang: str = "ru") -> List[dict]:
    """Return this module's questions WITHOUT server-side answer fields.

    Each returned item is ``{"id", "text", "options"}`` — ``correct_idx`` and
    ``explanation`` are stripped so the correct answers never reach the client.
    Returns an empty list for a module with no quiz (e.g. M8).
    """
    out = []
    for q in _bank_for(lesson_id):
        if lang == "en" and q.get("text_en"):
            out.append({"id": q["id"], "text": q["text_en"],
                        "options": list(q.get("options_en") or q["options"])})
        else:
            out.append({"id": q["id"], "text": q["text"], "options": list(q["options"])})
    return out


def passing_threshold(lesson_id: int) -> int:
    """Number of correct answers required to pass (ceil of 80%)."""
    n = len(_bank_for(lesson_id))
    if n == 0:
        return 0
    return int(math.ceil(PASS_FRACTION * n))


def grade_answers(lesson_id: int, answers: List[int]) -> dict:
    """Grade *answers* (list of chosen option indices) against the bank.

    Returns ``{"score": float, "passed": bool, "feedback": list[str]}``.
      - ``score`` is the percentage correct (0.0–100.0).
      - ``passed`` is True iff correct count >= ceil(80% of questions).
      - ``feedback`` is one human string per question — right/wrong plus the
        explanation. It NEVER reveals the correct option index or text of an
        unanswered-correctly question beyond the pre-authored explanation.

    An empty bank (M8) auto-passes: score=100.0, passed=True, feedback=[].
    Extra/short/None answers grade as wrong for the corresponding question
    (no exception): only an in-range index equal to correct_idx counts.
    """
    bank = _bank_for(lesson_id)
    if not bank:
        # M8 capstone / any answer-less module: automatic pass.
        return {"score": 100.0, "passed": True, "feedback": []}

    answers = list(answers) if answers is not None else []
    correct = 0
    feedback: List[str] = []
    for i, q in enumerate(bank):
        chosen = answers[i] if i < len(answers) else None
        is_right = isinstance(chosen, int) and chosen == q["correct_idx"]
        if is_right:
            correct += 1
            feedback.append(f"Вопрос {q['id']}: верно. {q['explanation']}")
        else:
            feedback.append(f"Вопрос {q['id']}: неверно. {q['explanation']}")

    n = len(bank)
    score = round(100.0 * correct / n, 2)
    passed = correct >= passing_threshold(lesson_id)
    return {"score": score, "passed": passed, "feedback": feedback}
