#!/bin/bash
# SPA Session Push — v4.67
# Дата: 2026-06-12
# Запускать: bash ~/Documents/SPA_Claude/scripts/push_all_session.sh
#
# Пушит все файлы созданные/изменённые в сессии 2026-06-12 (229 файлов).
# PAT читается из macOS Keychain (GITHUB_PAT_SPA) автоматически.

set -e
cd ~/Documents/SPA_Claude

echo "🚀 SPA Session Push v4.67 — 229 файлов..."

python3 push_to_github.py \
  --files \
  /Users/yuriikulieshov/Documents/SPA_Claude/.github/workflows/spa-lint.yml \
  /Users/yuriikulieshov/Documents/SPA_Claude/CLAUDE.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/CURRENT_STATE.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/KANBAN.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/PUSH_SESSION_v4.67.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/RULES.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/SPA_audit_report.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/SPA_sprint_log.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/SYSTEM_HEALTH.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/_run_spa_v434.sh \
  /Users/yuriikulieshov/Documents/SPA_Claude/_run_tests_mp071.command \
  /Users/yuriikulieshov/Documents/SPA_Claude/auto_push.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/com.spa.autopush.plist \
  /Users/yuriikulieshov/Documents/SPA_Claude/com.spa.httpserver.plist \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/adapter_orchestrator_status.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/adapter_status.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/agent_summaries.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/analytics_scorecard.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/analytics_summary.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/apy_dispersion_analytics.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/audit_trail.jsonl \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/backtest_vs_paper.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/bias_ratio.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/concentration_analytics.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/correlation_analytics.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/cost_drag_analytics.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/current_positions.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/daily_report_2026-06-12.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/dashboard_metrics_history.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/data_integrity_status.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/decisions.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/deflated_sharpe.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/drawdown_analytics.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/drawdown_attribution.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/equity_curve_daily.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/exit_liquidity_status.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/fast_loop_status.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/gap_monitor.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/golive_status.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/governance_proposals.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/honest_metrics.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/incidents.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/investor_portal_data.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/investors.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/kill_switch_status.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/last_approved_allocation.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/legal_status.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/llm_forbidden_lint.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/orchestrator_runs.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/orchestrator_trigger.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/paper_trading_status.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/pat_rotation_state.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/pnl_history.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/progress_tracker.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/rachev_ratio.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/rate_limiter_state.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/red_flags.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/regime_conditional_performance.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/reporting_status.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/risk_contribution.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/risk_scores.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/shadow_portfolio.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/slow_loop_insights.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/statements/2026-06_i1.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/statements/2026-06_i2.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/strategy_shadow_comparison.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/structural_break.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/tail_risk.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/tear_sheet.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/tg_update_offset.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/trades.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/turnover_analytics.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/ulcer_index.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/upside_potential_ratio.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/watchdog_cycle_result.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/watchdog_log.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/watchdog_state.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/yield_attribution.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/data/yield_decay_analytics.json \
  /Users/yuriikulieshov/Documents/SPA_Claude/docs/ADR_E2E_FORK_HARNESS.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/docs/ADR_TOKEN_VS_EQUITY.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/docs/AUDIT_online_v2.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/docs/AUDIT_status_backlog_v2.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/docs/AUDIT_team_papertest_v2.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/docs/AUDIT_v2_dashboard.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/docs/CHECKPOINT_v2.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/docs/DECISIONS.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/docs/FAMILY_FUND_ROADMAP.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/docs/LEGAL_STRUCTURE_v1.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/docs/LEVERAGE_STRATEGIES.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/docs/OUTREACH_STRATEGY_v1.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/docs/PHASE2_ROADMAP.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/docs/REPORT_v2_dashboard.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/docs/YIELD_STRATEGY_ROADMAP.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/docs/adr/ADR-010-gnosis-safe-key-management.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/docs/adr/ADR-011-go-live-security-checklist.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/docs/adr/ADR-019-t2-cap-increase.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/docs/adr/ADR-020-t3-private-credit.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/docs/kill_switch_drill.md \
  /Users/yuriikulieshov/Documents/SPA_Claude/index.html \
  /Users/yuriikulieshov/Documents/SPA_Claude/investor_portal.html \
  /Users/yuriikulieshov/Documents/SPA_Claude/push_mp129.command \
  /Users/yuriikulieshov/Documents/SPA_Claude/push_mp130.command \
  /Users/yuriikulieshov/Documents/SPA_Claude/push_mp135.command \
  /Users/yuriikulieshov/Documents/SPA_Claude/scripts/golive_preflight.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/scripts/kill_switch_drill.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/scripts/lint_llm_forbidden.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/scripts/pat_rotation_helper.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/scripts/push_all_session.sh \
  /Users/yuriikulieshov/Documents/SPA_Claude/scripts/tests/test_golive_preflight.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/scripts/tests/test_kill_switch_drill.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/scripts/tests/test_lint_llm_forbidden.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/adapters/__init__.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/adapters/pendle_adapter.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/agents/reporting_agent.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/alerts/alert_manager.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/alerts/bot_commands.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/alerts/daily_report.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/alerts/milestone_alert.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/alerts/telegram_format_ru.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/audit/data_integrity.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/audit/decision_audit.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/execution/__init__.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/execution/rate_limiter.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/family_fund/__init__.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/family_fund/models.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/family_fund/pnl_attribution.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/family_fund/registry.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/family_fund/telegram_blast.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/orchestrator/adapter_orchestrator.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/alpha_decay.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/analytics_scorecard.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/apy_dispersion_analytics.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/backtest_vs_paper.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/bias_ratio.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/capm_decomposition.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/concentration_analytics.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/correlation_analyzer.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/cost_drag_analytics.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/cycle_gap_monitor.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/cycle_runner.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/daily_report.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/deflated_sharpe.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/drawdown_analytics.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/drawdown_attribution.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/exit_liquidity.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/honest_metrics.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/liquidity_depth_analyzer.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/monthly_report.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/performance_report.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/position_sizing_v2.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/progress_tracker.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/protocol_scorecard.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/rachev_ratio.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/regime_conditional_performance.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/regime_detector.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/risk_contribution.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/strategy_consolidator.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/strategy_registry.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/structural_break.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/tail_risk.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/tournament_evaluator.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/turnover_analytics.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/ulcer_index.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/upside_potential_ratio.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/vportfolio.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/walk_forward_validator.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/yield_attribution.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/paper_trading/yield_decay_analytics.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/reporting/portal_data.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/risk/chain_limits.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/risk/policy.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/strategies/emode_looping.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/strategies/strategy_registry.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/testing/__init__.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/testing/fork_harness.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_alpha_decay.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_analytics_scorecard.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_apy_dispersion_analytics.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_backtest_vs_paper.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_bias_ratio.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_capm_decomposition.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_concentration_analytics.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_correlation_analyzer.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_cost_drag_analytics.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_cycle_gap_monitor.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_dashboard_snapshot.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_data_integrity.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_decision_audit.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_deflated_sharpe.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_drawdown_analytics.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_drawdown_attribution.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_exit_liquidity.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_family_fund.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_fork_harness.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_honest_metrics.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_l2_adapters.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_milestone_alert.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_monthly_report.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_paper_trading_daily_report.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_pat_rotation.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_pendle_adapter.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_performance_report.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_portal_data.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_position_sizing_v2.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_progress_tracker.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_protocol_scorecard.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_rachev_ratio.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_rate_limiter.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_regime_conditional_performance.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_regime_detector.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_risk_contribution.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_risk_policy.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_strategy_consolidator.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_structural_break.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_tail_risk.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_telegram_alerts.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_tournament_evaluator.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_turnover_analytics.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_ulcer_index.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_upside_potential_ratio.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_vportfolio.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_walk_forward_validator.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_yield_attribution.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/tests/test_yield_decay_analytics.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/utils/__init__.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/spa_core/utils/refresh_agent_summaries.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/tests/test_liquidity_depth_analyzer.py \
  /Users/yuriikulieshov/Documents/SPA_Claude/tests/test_telegram_formatting.py \
  --message "feat(v4.67): Batch push session — tournament, leverage, family fund, preflight, analytics [229 files]"

echo "✅ Push завершён!"
