#!/usr/bin/env python3
"""
scripts/test_coverage_report.py
Test coverage analysis for SPA codebase.
Reports: tested modules, untested modules, test density.

MP-1519 (v11.35) — stdlib only, no external dependencies.

Usage:
    python3 scripts/test_coverage_report.py
    python3 scripts/test_coverage_report.py --spa-dir spa_core --test-dir tests
    python3 scripts/test_coverage_report.py --output docs/TEST_COVERAGE_REPORT.md
    python3 scripts/test_coverage_report.py --json
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path


def count_tests_in_file(path: Path) -> int:
    """Count `def test_*` functions in a test file."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
        return sum(
            1 for line in text.splitlines()
            if line.strip().startswith("def test_")
        )
    except OSError:
        return 0


def analyze_coverage(
    spa_dir: str = "spa_core",
    test_dir: str = "tests",
) -> dict:
    """
    Analyze test coverage across the SPA codebase.

    Returns a dict with:
      total_modules    — number of .py files in spa_dir (excl. __init__, __pycache__)
      tested           — number with at least one matching test file
      untested         — number with no matching test file
      coverage_pct     — tested / total * 100
      total_tests      — sum of def test_ across all test files
      test_files_total — total test files in test_dir
      top_untested     — first 40 untested module paths (sorted)
      tested_detail    — list of {module, test_count, test_files}
      by_package       — coverage breakdown by top-level package
    """
    spa_path = Path(spa_dir)
    test_path = Path(test_dir)

    # Gather all spa_core module files
    all_modules: list[Path] = []
    for root, dirs, files in os.walk(spa_path):
        dirs[:] = sorted(d for d in dirs if d != "__pycache__")
        for f in sorted(files):
            if f.endswith(".py") and not f.startswith("__"):
                all_modules.append(Path(root) / f)

    # Gather all test files
    test_files_total = len(list(test_path.glob("test_*.py"))) if test_path.exists() else 0

    # Match modules to test files
    tested_detail: list[dict] = []
    untested: list[str] = []

    # Also track by package (second-level directory under spa_core)
    by_package: dict[str, dict] = {}

    for module in all_modules:
        stem = module.stem
        rel_parts = module.relative_to(spa_path).parts
        pkg = rel_parts[0] if len(rel_parts) > 1 else "root"
        if pkg not in by_package:
            by_package[pkg] = {"total": 0, "tested": 0}
        by_package[pkg]["total"] += 1

        matching = sorted(test_path.glob(f"test_{stem}*.py")) if test_path.exists() else []
        # Also check spa_core/tests/ pattern
        spa_tests = Path(spa_dir) / "tests"
        if spa_tests.exists():
            matching += sorted(spa_tests.glob(f"test_{stem}*.py"))

        if matching:
            test_count = sum(count_tests_in_file(tf) for tf in matching)
            tested_detail.append({
                "module": str(module),
                "test_count": test_count,
                "test_files": [str(tf) for tf in matching],
            })
            by_package[pkg]["tested"] += 1
        else:
            untested.append(str(module))

    total_modules = len(all_modules)
    tested_count = len(tested_detail)
    total_tests = sum(t["test_count"] for t in tested_detail)

    # Sort untested for stable output
    untested_sorted = sorted(untested)

    return {
        "total_modules": total_modules,
        "tested": tested_count,
        "untested": total_modules - tested_count,
        "coverage_pct": (tested_count / total_modules * 100) if total_modules else 0.0,
        "total_tests": total_tests,
        "test_files_total": test_files_total,
        "top_untested": untested_sorted[:40],
        "all_untested_count": len(untested_sorted),
        "tested_detail": sorted(tested_detail, key=lambda x: -x["test_count"])[:30],
        "by_package": by_package,
    }


def format_markdown(result: dict, spa_dir: str, test_dir: str) -> str:
    """Format coverage report as Markdown."""
    lines: list[str] = []
    lines.append("# SPA Test Coverage Report")
    lines.append("")
    lines.append("> Generated by `scripts/test_coverage_report.py`  ")
    lines.append(f"> spa_dir: `{spa_dir}` | test_dir: `{test_dir}`")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|---|---|")
    lines.append(f"| Total modules | {result['total_modules']} |")
    lines.append(f"| Tested modules | {result['tested']} |")
    lines.append(f"| Untested modules | {result['untested']} |")
    lines.append(f"| Coverage | **{result['coverage_pct']:.1f}%** |")
    lines.append(f"| Total test functions | {result['total_tests']:,} |")
    lines.append(f"| Test files (`tests/`) | {result['test_files_total']} |")
    lines.append("")

    # Progress bar
    pct = result["coverage_pct"]
    filled = int(pct / 5)  # 20 blocks for 100%
    bar = "█" * filled + "░" * (20 - filled)
    lines.append(f"Coverage: `[{bar}]` {pct:.1f}%")
    lines.append("")

    # By package
    lines.append("## Coverage by Package")
    lines.append("")
    lines.append("| Package | Modules | Tested | Coverage |")
    lines.append("|---|---|---|---|")
    for pkg, stats in sorted(result["by_package"].items()):
        pkg_pct = (stats["tested"] / stats["total"] * 100) if stats["total"] else 0.0
        flag = "✅" if pkg_pct >= 80 else ("⚠️" if pkg_pct >= 40 else "❌")
        lines.append(f"| `{pkg}` | {stats['total']} | {stats['tested']} | {flag} {pkg_pct:.0f}% |")
    lines.append("")

    # Top tested modules (most tests)
    lines.append("## Best Covered Modules (top 10 by test count)")
    lines.append("")
    lines.append("| Module | Test functions |")
    lines.append("|---|---|")
    for item in result["tested_detail"][:10]:
        lines.append(f"| `{item['module']}` | {item['test_count']} |")
    lines.append("")

    # Untested modules
    lines.append(f"## Untested Modules ({result['all_untested_count']} total, showing first 40)")
    lines.append("")
    lines.append("These modules have no matching `test_<module>*.py` file:")
    lines.append("")
    for m in result["top_untested"]:
        lines.append(f"- `{m}`")
    if result["all_untested_count"] > 40:
        lines.append(f"- … and {result['all_untested_count'] - 40} more")
    lines.append("")

    # Recommendations
    lines.append("## Recommendations")
    lines.append("")
    untested_critical = [
        m for m in result["top_untested"]
        if any(kw in m for kw in ["risk", "allocator", "golive", "cycle_runner", "safety"])
    ]
    if untested_critical:
        lines.append("### Critical gaps (risk/safety/core paths):")
        lines.append("")
        for m in untested_critical[:10]:
            lines.append(f"- `{m}`")
        lines.append("")

    pct = result["coverage_pct"]
    if pct < 50:
        lines.append("**Status: 🔴 LOW** — coverage below 50%. Prioritize critical path modules.")
    elif pct < 80:
        lines.append("**Status: 🟡 MEDIUM** — coverage 50–80%. Focus on untested risk/execution paths.")
    else:
        lines.append("**Status: 🟢 HIGH** — coverage above 80%. Maintain and improve edge case coverage.")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="SPA test coverage analyzer",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument("--spa-dir", default="spa_core", help="spa_core directory")
    parser.add_argument("--test-dir", default="tests", help="tests directory")
    parser.add_argument("--output", default=None, help="Write Markdown report to file")
    parser.add_argument("--json", action="store_true", help="Print JSON output")
    args = parser.parse_args()

    result = analyze_coverage(spa_dir=args.spa_dir, test_dir=args.test_dir)

    if args.json:
        print(json.dumps(result, indent=2))
        return

    # Console summary
    print(f"Coverage: {result['tested']}/{result['total_modules']} modules ({result['coverage_pct']:.1f}%)")
    print(f"Total tests: {result['total_tests']:,}")
    print(f"Test files: {result['test_files_total']}")
    print(f"Untested ({result['all_untested_count']} modules, first 20):")
    for m in result["top_untested"][:20]:
        print(f"  {m}")

    # Write markdown
    md = format_markdown(result, args.spa_dir, args.test_dir)
    if args.output:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        # Atomic write
        import tempfile
        dir_ = str(out_path.parent)
        fd, tmp = tempfile.mkstemp(dir=dir_, suffix=".tmp")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as f:
                f.write(md)
            os.replace(tmp, str(out_path))
        except Exception:
            try:
                os.unlink(tmp)
            except OSError:
                pass
            raise
        print(f"\nReport written: {args.output}")
    else:
        print("\n--- Markdown preview (first 30 lines) ---")
        for line in md.splitlines()[:30]:
            print(line)


if __name__ == "__main__":
    main()
